config/routes.rb
Pinteresting::Application.routes.draw do
  root "pages#home"
  get "about" => "pages#about" #creates about path
  get "team" => "pages#team" #creates team path
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Team", team_path %></li>
   
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render "layouts/header" %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About this site</h1>
<p>This will be something interesting the next time you see it.</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>This is my app homepage</h1>
	<p>There are many like it, but this is my own.</p>

	<%= link_to "Login", "#", class: "btn btn-primary btn-lg" %>
	<%= link_to "Sign Up", "#", class: "btn btn-success btn-lg" %>
</div>

app/views/pages/team.html.erb
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("128.jpg", alt: "Slothey") %>
      <div class="caption center">
        <h3>Steven Jennsen</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia felis et fermentum laoreet. Aliquam erat volutpat. Integer commodo arcu vel purus vulputate dapibus et nec orci. Maecenas non faucibus nisl, et commodo nibh. Aliquam erat volutpat. Quisque faucibus, felis eget convallis venenatis, diam ligula luctus odio.</p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("128-1.jpg", alt: "Vinylo") %>
      <div class="caption center">
        <h3>Rockey Ruth</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia felis et fermentum laoreet. Aliquam erat volutpat. Integer commodo arcu vel purus vulputate dapibus et nec orci. Maecenas non faucibus nisl, et commodo nibh. Aliquam erat volutpat. Quisque faucibus, felis eget convallis venenatis, diam ligula luctus odio.</p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("128-2.jpg", alt: "Doge") %>
      <div class="caption center">
        <h3>Jerry Ghergins</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia felis et fermentum laoreet. Aliquam erat volutpat. Integer commodo arcu vel purus vulputate dapibus et nec orci. Maecenas non faucibus nisl, et commodo nibh. Aliquam erat volutpat. Quisque faucibus, felis eget convallis venenatis, diam ligula luctus odio.</p>
      </div>
    </div>
  </div>
</div>